version: '3.8'

services:
  backend:
    container_name: crimedb
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/src
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/crime
    depends_on:
      - rabbitmq
      - mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  mysql:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=crime

volumes:
  db:
    driver: local